neo4j/cypher-dsl

src/main/java/org/neo4j/cypherdsl/CypherQuery.java
src/main/java/org/neo4j/cypherdsl/Identifier.java
src/main/java/org/neo4j/cypherdsl/LabelReference.java
src/main/java/org/neo4j/cypherdsl/Property.java
src/main/java/org/neo4j/cypherdsl/expression/RemoveExpression.java
src/main/java/org/neo4j/cypherdsl/query/clause/RemoveClause.java
src/test/java/org/neo4j/cypherdsl/CypherReferenceTest.java

Implemented Remove labels.

---

src/main/java/org/neo4j/cypherdsl/CypherQuery.java
src/main/java/org/neo4j/cypherdsl/Identifier.java
src/main/java/org/neo4j/cypherdsl/LabelReference.java
src/main/java/org/neo4j/cypherdsl/expression/SetExpression.java
src/main/java/org/neo4j/cypherdsl/grammar/ForEachStatement.java
src/main/java/org/neo4j/cypherdsl/grammar/ForEachStatements.java
src/main/java/org/neo4j/cypherdsl/grammar/OnCreate.java
src/main/java/org/neo4j/cypherdsl/grammar/OnMatch.java
src/main/java/org/neo4j/cypherdsl/grammar/Set.java
src/main/java/org/neo4j/cypherdsl/query/clause/ForEachClause.java
src/main/java/org/neo4j/cypherdsl/query/clause/OnCreateClause.java
src/main/java/org/neo4j/cypherdsl/query/clause/OnMatchClause.java
src/main/java/org/neo4j/cypherdsl/query/clause/SetClause.java
src/test/java/org/neo4j/cypherdsl/CypherReferenceTest.java

Added the ability to set labels in a set clause.
Added supporting test cases.
Cleaned up some code duplication in Identifier.java
closes #46

Implement labels in Set clause

---

neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/Functions.java
neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/CypherIT.java

Add a factory method to create a point from a provided parameter.

---

neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/BuiltInFunctions.java
neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/Functions.java
neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/StatementBuilder.java
neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/FunctionsIT.java

GH-77 - Add support for properties().

---

neo4j-cypher-dsl-examples/src/test/java/org/neo4j/cypherdsl/examples/core/CypherDSLExamplesTest.java
neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/ProcedureCall.java

GH-82 - Expose union interfaces for call related builders.

---

neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/BuiltInFunctions.java
neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/Functions.java
neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/FunctionsIT.java

Support for
`relationships()` (GH-81)
`startNode()` and `endNode` (GH-83)
closes #81 
closes #83

Additional functions

---

neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/renderer/RenderingVisitor.java
neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/support/TypedSubtree.java
neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/CypherIT.java

GH-84 - Fix rendering of nested sub trees.

---

neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/SymbolicName.java

Bring back the SymbolicName#concat.

---

neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/MapProjection.java
neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/CypherIT.java

This is needed as node and relationships are not expressions.

Check for named new content while adding additional projections.

---

neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/Cypher.java
neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/PatternComprehension.java
neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/CypherIT.java

This is a little bit inception-like because I opened the PR for your changes.
But those are still missing from the main branch ;)

Add API for creating list comprehensions based on named paths.

---

neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/Cypher.java
neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/DefaultStatementBuilder.java
neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/Limit.java
neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/Skip.java
neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/StatementBuilder.java
neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/CypherIT.java

Allow Expressions as Parameter for Skip and Limit

---

neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/ConstantCondition.java
neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/ExpressionCondition.java
neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/SymbolicName.java
neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/IssueRelatedIT.java

Allow named objects to be used as condition

---

neo4j-cypher-dsl-examples/src/test/java/org/neo4j/cypherdsl/examples/core/PropertiesTest.java
neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/Cypher.java
neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/ExposesProperties.java
neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/MapExpression.java
neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/CypherIT.java

GH-157 - Provide a method to turn a Java map into an expression.

---

neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/Cypher.java
neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/DefaultStatementBuilder.java
neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/ExposesCreate.java
neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/ExposesMatch.java
neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/StatementBuilder.java
neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/CypherIT.java
neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/CypherTest.java
neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/IssueRelatedIT.java
neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/ProcedureCallsIT.java

This PR adds a parallel API to the already existing var-args exposing methods.
Closes #189

Provide a parallel Collection based API to the var-args parameters.

---

neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/DefaultStatementBuilder.java
neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/ExposesReturning.java
neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/CypherIT.java

GH-195 - Add collection parameter support for ExposesReturning.

---

README.adoc
neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/Expression.java
neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/IssueRelatedIT.java
pom.xml

feat: Add `size` and `hasSize` on expressions.

---

.github/workflows/build.yml

Pull request for verification.

Use official GraalVM GitHub action.

---

neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/ExpressionList.java
neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/Subquery.java
neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/IssueRelatedIT.java

bug: Don't create empty `WITH` clause without renames.

---

neo4j-cypher-dsl-parser/src/main/java/org/neo4j/cypherdsl/parser/CypherDslASTFactory.java
neo4j-cypher-dsl-parser/src/main/java/org/neo4j/cypherdsl/parser/ExpressionCreatedEventType.java
neo4j-cypher-dsl-parser/src/test/java/org/neo4j/cypherdsl/parser/RewriteTest.java

This is useful for JDBC prepared statements e.g.

Implement support for parameter callbacks

---

README.adoc
neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/StatementBuilder.java
neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/IssueRelatedIT.java

feat: Allow procedure calls without results after a match clause.

---

README.adoc
neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/AbstractPropertyContainer.java
neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/MessageKeys.java
neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/PropertyContainer.java
neo4j-cypher-dsl/src/main/resources/org/neo4j/cypherdsl/core/messages.properties
neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/InternalNodeImplTest.java
neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/IssueRelatedIT.java

This aligns with the `mutate` API and hopefully guides users better. It
closes #388.

feat: Add explicit `set` operation to `PropertyContainer`.

---

docs/static-meta-model/possible-usage.adoc
docs/static-meta-model/sdn6-annotation-processor.adoc
neo4j-cypher-dsl-examples/neo4j-cypher-dsl-examples-sdn6/src/main/java/org/neo4j/cypherdsl/examples/sdn6/movies/NewPersonCmd.java
neo4j-cypher-dsl-examples/neo4j-cypher-dsl-examples-sdn6/src/main/java/org/neo4j/cypherdsl/examples/sdn6/movies/PeopleController.java
neo4j-cypher-dsl-examples/neo4j-cypher-dsl-examples-sdn6/src/main/java/org/neo4j/cypherdsl/examples/sdn6/movies/PeopleService.java
neo4j-cypher-dsl-examples/neo4j-cypher-dsl-examples-sdn6/src/test/java/org/neo4j/cypherdsl/examples/sdn6/ApplicationIT.java
neo4j-cypher-dsl-examples/neo4j-cypher-dsl-examples-sdn6/src/test/resources/logback-test.xml

docs: Add an example how to use Cypher parameters with`CypherdslStatementExecutor`.

---

neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/internal/ScopingStrategy.java
neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/IssueRelatedIT.java

fix: Include aliased expression in local scopes.

---

neo4j-cypher-dsl-examples/neo4j-cypher-dsl-examples-parser/src/test/java/org/neo4j/cypherdsl/examples/parser/CypherDSLParserExamplesTest.java
neo4j-cypher-dsl-parser/src/main/java/org/neo4j/cypherdsl/parser/CypherDslASTFactory.java
neo4j-cypher-dsl-parser/src/main/java/org/neo4j/cypherdsl/parser/ExpressionCreatedEventType.java

feat: Provide `ON_DELETE_ITEM` event type.

---

.github/workflows/build.yml
neo4j-cypher-dsl-schema-name-support/src/test/java/org/neo4j/cypherdsl/support/schema_name/SchemaNamesIT.java

build: Fix the build on a restricted TeamCity instance.

---

neo4j-cypher-dsl-schema-name-support/src/main/java/org/neo4j/cypherdsl/support/schema_name/SchemaNames.java

docs: Add missing value to `sanitize` JavaDoc.

---

bin/remove-shaded-modules.sh
neo4j-cypher-dsl/pom.xml
neo4j-cypher-dsl/src/main/java/module-info.java
pom.xml

This leads to endless pain with the proper module support.

refactor: Stop shading the schema-name support.

---

neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/BuiltInFunctions.java
neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/Functions.java
neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/MessageKeys.java
neo4j-cypher-dsl/src/main/resources/org/neo4j/cypherdsl/core/messages.properties
neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/FunctionsIT.java

feat: Add `length()` function.

---

neo4j-cypher-dsl-parser/src/test/java/org/neo4j/cypherdsl/parser/ComparisonIT.java
neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/ParameterCollectingVisitor.java
neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/internal/FixedNamesStrategy.java
neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/internal/GeneratedNamesStrategy.java
neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/internal/NameResolvingStrategy.java
neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/renderer/Configuration.java
neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/renderer/DefaultVisitor.java
neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/renderer/ConfigurableRendererTest.java

feat: Use generated names for aliases too if possible.

---

neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/Cypher.java
neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/MapLiteral.java
neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/CypherTest.java
neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/IssueRelatedIT.java

Adds support for creating `Map` literals via `Cypher.literalOf`.

Adds support for Map literals

---

neo4j-cypher-dsl-parser/src/test/java/org/neo4j/cypherdsl/parser/ComparisonIT.java
neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/internal/GeneratedNamesStrategy.java
neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/renderer/DefaultVisitor.java
neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/renderer/ConfigurableRendererTest.java

refactor: Replace identifiers in list / pattern comprehensions, too.

---

neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/renderer/Configuration.java
neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/renderer/Dialect.java
neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/DialectIT.java
neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/renderer/ConfigurationTest.java

refactor: Replace `DEFAULT` dialect with explicit `NEO4J_4` dialect.

---

neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/DefaultStatementBuilder.java
neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/Delete.java
neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/Foreach.java
neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/Set.java
neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/StatementBuilder.java
neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/UpdatingClause.java
neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/CypherIT.java
neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/DeleteTest.java

feat: Add builder methods for `FOREACH`.

---

neo4j-cypher-dsl-examples/neo4j-cypher-dsl-examples-parser/src/test/java/org/neo4j/cypherdsl/examples/parser/StatementCatalogBuildingVisitorViaParserTest.java
neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/ListOperator.java
neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/LiteralBase.java
neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/Merge.java
neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/StatementCatalog.java
neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/StatementCatalogBuildingVisitor.java
neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/StatementCatalogBuildingVisitorTest.java

feat: Allow retrieval of literals.

---

neo4j-cypher-dsl-examples/neo4j-cypher-dsl-examples-parser/src/test/java/org/neo4j/cypherdsl/examples/parser/CypherDSLParserExamplesTest.java
neo4j-cypher-dsl-parser/src/main/java/org/neo4j/cypherdsl/parser/CypherDslASTFactory.java
neo4j-cypher-dsl-parser/src/main/java/org/neo4j/cypherdsl/parser/ExpressionCreatedEventType.java
neo4j-cypher-dsl-parser/src/test/java/org/neo4j/cypherdsl/parser/CypherParserTest.java
neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/Asterisk.java
neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/BooleanLiteral.java
neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/DriverValueAdapter.java
neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/DurationLiteral.java
neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/ListLiteral.java
neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/ListOperator.java
neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/Literal.java
neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/LiteralBase.java
neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/MapLiteral.java
neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/Merge.java
neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/NumberLiteral.java
neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/PeriodLiteral.java
neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/RawLiteral.java
neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/StringLiteral.java
neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/internal/Namespace.java
neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/internal/ProcedureName.java
neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/ToStringSmokeTest.java

This allows for example to rewrite String literals as parameters, example included.
Closes #739

feat: Introduce event to capture parsed literals.

---

README.adoc
neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/DefaultStatementBuilder.java
neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/MergeAction.java
neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/StatementBuilder.java
neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/CypherIT.java
pom.xml

feat: Allow `REMOVE` being used after `MERGE`.

---

neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/ExposesRelationships.java
neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/IssueRelatedIT.java

feat: Provide non-builder method for creating relationships.

---

README.adoc
neo4j-cypher-dsl-parser/src/main/java/org/neo4j/cypherdsl/parser/CypherDslASTFactory.java
neo4j-cypher-dsl-parser/src/main/java/org/neo4j/cypherdsl/parser/InvocationCreatedEventType.java
neo4j-cypher-dsl-parser/src/main/java/org/neo4j/cypherdsl/parser/Options.java
neo4j-cypher-dsl-parser/src/test/java/org/neo4j/cypherdsl/parser/CypherParserTest.java

feat: Add callbacks for function and procedure invocations.

---

neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/BuiltInFunctions.java
neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/Predicates.java
neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/FunctionsIT.java

feat: Add `isEmpty()`.

---

neo4j-cypher-dsl-examples/neo4j-cypher-dsl-examples-driver/src/test/java/org/neo4j/cypherdsl/examples/drivers/GeneratedConditionsIT.java
neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/Conditions.java
neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/CypherIT.java

fix: Apply the correct includesAll and includesAny semantics

---

neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/internal/ScopingStrategy.java
neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/IssueRelatedIT.java

fix: Recognize entities defined in sub-queries correctly.

---

README.adoc
neo4j-cypher-dsl-codegen/neo4j-cypher-dsl-codegen-core/src/main/java/org/neo4j/cypherdsl/codegen/core/Configuration.java
neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/CollectExpression.java
neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/Expressions.java
neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/SubqueryExpression.java
neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/internal/ScopingStrategy.java
neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/renderer/DefaultVisitor.java
neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/SubqueriesIT.java

feat: Add support for `COLLECT` subqueries.

---

neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/Clauses.java
neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/DefaultStatementBuilder.java
neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/ExposesSubqueryCall.java
neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/Subquery.java
neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/renderer/DefaultVisitor.java
neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/renderer/PrettyPrintingVisitor.java
neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/IssueRelatedIT.java
neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/SubqueriesIT.java

refactor: Allow unit-subqueries.

---

neo4j-cypher-dsl-parser/src/test/java/org/neo4j/cypherdsl/parser/RewriteTest.java
neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/Parameter.java

Backport of ee28ac9 to 2022.9.x branch.

feat: Allow retrieving parameter names

---

README.adoc
neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/Cypher.java
neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/CypherIT.java
pom.xml

Adds a new `callRawCypher` method to the top level `Cypher` entry point.

feat: add call raw cypher to top level entry point

---

.github/workflows/build.yml
README.adoc
neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/Cypher.java
neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/CypherIT.java
pom.xml

feat: add call raw cypher to top level entry point (#1073)

---

README.adoc
neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/AbstractNode.java
neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/HasLabelExpressionCondition.java
neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/Node.java
neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/LabelExpressionTest.java

feat: Add `hasLabels(LabelExpression labels)` for nodes.

---

neo4j-cypher-dsl-parser/src/test/java/org/neo4j/cypherdsl/parser/ComparisonIT.java
neo4j-cypher-dsl-parser/src/test/java/org/neo4j/cypherdsl/parser/CypherParserTest.java
neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/internal/ScopingStrategy.java

To me the result looks plausible in this form, but would be good to get another pair of eyes on this.

fix: Fix scoping issue with existential subquery
