- pom.xml
- src/main/java/org/neo4j/cypherdsl/querydsl/CypherQueryDSL.java
- src/main/java/org/neo4j/cypherdsl/querydsl/Projection.java
- src/test/java/org/neo4j/cypherdsl/querydsl/Person.java
- src/test/java/org/neo4j/cypherdsl/querydsl/Place.java
- src/test/java/org/neo4j/cypherdsl/querydsl/QueryDSLTest.java
- src/test/java/org/neo4j/cypherdsl/querydsl/Stuff.java
Upgrade to querydsl 4.0.x.
Minor dependency upgrades to the querydsl infrastructure.
Upgraded querydsl.version to 4.0.6 to move away from the now 
unsupported mysema querydsl version.
Corrected imports and adapted internals to new com.querydsl API.
Fixes #49.
> Upgrade to querydsl 4.0.x.

- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/Arguments.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/Cypher.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/DefaultStatementBuilder.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/ExposesCall.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/ExposesProperties.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/ExpressionList.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/Expressions.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/ListExpression.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/MapExpression.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/MapProjection.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/Node.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/Order.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/Pattern.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/ProcedureCall.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/Properties.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/Relationship.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/RelationshipChain.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/SinglePartQuery.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/StatementBuilder.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/YieldItems.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/renderer/CypherRenderer.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/support/TypedSubtree.java
- neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/CypherIT.java
- neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/CypherTest.java
This fixes a couple of places in which generics have put to use that are actually not fulfillable by any implementation, i.e. on final classes. Those makes of course now sense and has been fixed.
Furthermore, some return types on the entry points have changed, which may need recompiling dependents.
On a couple of methods unchecked conversions have been suppressed by `@SuppressWarnings("unchecked")` (all those that are actually safe).
> Clean up a couple of Generic crime scenes.

- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/BuiltInFunctions.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/Cypher.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/DistinctExpression.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/FunctionInvocation.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/Functions.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/NamedPath.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/Predicates.java
- neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/CypherIT.java
- neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/FunctionsIT.java
- neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/FunctionsTest.java
This introduces a formal `FunctionDefinition` that contains the implementation name of the function and a flag whether its an aggregate or not.
This definition is used for the build in scalars, aggregates and predicates now. It can be used in the future for user defined functions (udfs) as well. Furthermore it could cater for better static definitions, like argument cardinality and type.
It also adds a test for and closes #44.
> Clean up the Functions api.

- neo4j-cypher-dsl-examples/pom.xml
- neo4j-cypher-dsl/pom.xml
- pom.xml
This includes
- Setting a specific version in `README.adoc` so that the GH-Action uses the correct version when the documentation is generated and "current" http://neo4j-contrib.github.io/cypher-dsl/current points to that
Can be done now through
```
./mvnw exec:exec@prepare_release -Drevision=2020.0.2 -Dchangelist= -pl org.neo4j:neo4j-cypher-dsl-parent
./mvnw exec:exec@delete_readme_backup -pl org.neo4j:neo4j-cypher-dsl-parent
./mvnw scm:checkin@prepare_release
```
- Change back to the snapshot version afterwards so that the README itself is correct when looking at the main branch and also at the snapshot documentation under http://neo4j-contrib.github.io/cypher-dsl/main/
Implemented with
```
./mvnw exec:exec@prepare_release -pl org.neo4j:neo4j-cypher-dsl-parent
./mvnw …
```
> Automate release preparation and cleanup.

- docs/functions/index.adoc
- docs/functions/lists.adoc
- docs/getting-started/getting-started.adoc
- docs/getting-started/index.adoc
- docs/index.adoc
- docs/introduction-and-preface/index.adoc
- docs/introduction-and-preface/introduction.adoc
- neo4j-cypher-dsl-examples/src/test/java/org/neo4j/cypherdsl/examples/core/FunctionsListTest.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/Cypher.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/Functions.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/ListOperator.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/renderer/RenderingVisitor.java
- neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/CypherIT.java
Modelled after the openCypher ListOperator expression, `Cypher.rangeOf`, `Cypher.rangeStartingAt`, `Cypher.rangeUntil` and `Cypher.valueAt` can be used to create a list operation upon an expression. No sanity check if the expression resolved to a list is done at the moment. This closes #76.
@Andy2003 Would you please have a look if that suites your use case?
> GH-76 - Add ListOperator expression.

- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/BuiltInFunctions.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/Cypher.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/Functions.java
- neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/FunctionsIT.java
This add supports for most of the temporal functions. For date, it adds a couple of convinience methods. Otherwise the temporals can be called with map expressions, parameter expressions or string literals.
This fixes #89.
Please, @meistermeier have a quick look if I forgot something important or if you would generify the creation a bit (I wouldn't, I think the effort is not worth it).
> GH-89 - Add support for Neo4j’s temporal functions.

- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/AliasedExpression.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/renderer/RenderingVisitor.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/support/ReflectiveVisitor.java
- neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/CypherIT.java
This became appearent when trying to formulate
```
String query = ""
+ "MATCH (n:Order) - [r:HAS] -> (l:LineItem) "
+ "WHERE n.id = $id "
+ "WITH n, sum(l.price * l.quantity) AS netAmount, collect(r) as hasRel, collect(l) as lineItems "
+ "RETURN {"
+ " netAmount: netAmount,"
+ "	taxAmount: netAmount * $taxRate,"
+ " totalAmount: netAmount * (1+$taxRate),"
+ " hasRel: hasRel, lineItems: lineItems"
+ "}";
```
for the spring data neo4j native project.
> Make sure aliased expressions are not rendered multiple times.

- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/ExposesCall.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/ProcedureCall.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/ProcedureName.java
- neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/ProcedureCallsIT.java
This allows turning a custom stored procedure call into an expression to be used for example in properties, a set clause or as a parameter to other calls.
This closes #101.
> GH-101 - Introduce asFunction on an ongoing call definition.

- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/renderer/RenderingVisitor.java
- neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/CypherIT.java
- neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/renderer/RenderingVisitorTest.java
See https://neo4j.com/docs/cypher-manual/current/syntax/naming/#_naming_rules. While we do now escape symbolic names for completness, we do not allow creating them with non identifier names.
This closes #106.
Did I miss something, Gerrit?
> GH-106 - Escape symbolic names, property lookups, aliases and map keys. [bug]

- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/AbstractStatement.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/Statement.java
- neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/CypherIT.java
This change provides `getCypher()` on a `Statement` in parallel and symmetry for `getParameters` so that a statement can be seen as a fully, usable result.
> Allow a statement to render itself.

- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/renderer/DefaultVisitor.java
- neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/CypherIT.java
A node must be rendered completly after a `WITH` clause as long as it has not been carried forward in the body of that clause.
> Fix missing labels for nodes after `WITH`.

- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/Asterisk.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/BooleanLiteral.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/Cypher.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/ListLiteral.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/ListOperator.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/Literal.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/LiteralBase.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/Merge.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/NumberLiteral.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/RawLiteral.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/StringLiteral.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/TemporalLiteral.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/support/UnsupportedLiteralException.java
- neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/CypherIT.java
- neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/TemporalLiteralTest.java
This commit turns `Literal` into an interface and removes unwanted, external API. With that change in place, `Cypher.literalOf` tries to find more ways to turn an arbitrary object into a literal that Cypher respectively Neo4j can understand.
- It won’t fail immediate when a collection element isn’t a literal but instead try recursively to translate it
- It will translate arrays
- It will translate single characters
- It won’t fail on objects that are already literals
- It will translate several temporal accessors into Neo4j function calls that create the appropriate objects back from an ISO string
- It introduces UnsupportedLiteralException that allows to check explicitly for what object isn’t supported as literal
> Improve Cypher.literalOf. [new-feature]

- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/NamedPath.java
- neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/CypherIT.java
According to https://s3.amazonaws.com/artifacts.opencypher.org/M15/railroad/PatternElement.html the `Node`(Pattern) is a valid type in parallel to the `RelationshipPattern` for path definitions.
Maybe this is too naive from my side but it seems to not break anything else or broadens the API too much when supporting this.
Closes #200
> Add support for path with node.

- README.adoc
- neo4j-cypher-dsl-examples/neo4j-cypher-dsl-examples-parser/src/test/java/org/neo4j/cypherdsl/examples/parser/CypherDSLParserExamplesTest.java
- neo4j-cypher-dsl-parser/src/main/java/org/neo4j/cypherdsl/parser/CypherDslASTFactory.java
- neo4j-cypher-dsl-parser/src/main/java/org/neo4j/cypherdsl/parser/Options.java
- neo4j-cypher-dsl-parser/src/main/java/org/neo4j/cypherdsl/parser/PatternElementCreatedEventType.java
- neo4j-cypher-dsl-parser/src/test/java/org/neo4j/cypherdsl/parser/CypherParserTest.java
- neo4j-cypher-dsl-parser/src/test/java/org/neo4j/cypherdsl/parser/OptionsTest.java
This allows to intercept all kinds of pattern elements (nodes and relationships) when needed in both `CREATE` and `MATCH` clauses.
Also added examples how to use them as well as how to achieve something similar with filters.
Closes #299.
> feat: Add callbacks for a "pattern element created event".

- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/Operations.java
- neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/CypherIT.java
It seems some mutate value expressions are not supported with this error being thrown from `Operations.java#mutate`:
```
A property container can only be mutated by a map, or a parameter or property pointing to a map.
```
Refer to the added test cases for the new expression support added by this PR.  I'm not sure if there are other expression types that should also be considered (or if it might actually be better to just accept any `Expression` and allow the query to fail at runtime?).
> Support additional mutate expression types

- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/renderer/DefaultVisitor.java
- neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/CypherIT.java
When rendering AST that has nested `ForEach` clauses, there ends up being a missing `)` at the end because the `ForEach` renderer assumes a trailing space, and because `ForEach` also doesn't add a trailing space, if they are nested the outer `ForEach` ends up overwriting the closing `)` of the inner `ForEach` instead of adding a new one. 
This PR adds the trailing space to `ForEach` and test(s).
> Fix rendering of nested FOREACH statements

- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/renderer/DefaultVisitor.java
- neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/IssueRelatedIT.java
> fix: Don't skip symbolic names if present and already in scope.

- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/DefaultStatementBuilder.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/StatementBuilder.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/internal/ScopingStrategy.java
- neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/IssueRelatedIT.java
This allows to diverge from a procedure call without a result into a
regular flow and be explicit about the fact that a procedure doesn't
produce anything and is essentially just kind of a throwing validator.
This closes #349.
> refactor: Rework feature #84732cbd7 to be explicit.

- neo4j-cypher-dsl-parser/src/main/java/org/neo4j/cypherdsl/parser/CypherDslASTFactory.java
- neo4j-cypher-dsl-parser/src/test/java/org/neo4j/cypherdsl/parser/CypherParserTest.java
When parsing a statement that includes a `WITH` clause with a `*` AND other expressions:
```
WITH 'foo' AS foo
WITH *, 'bar' AS bar
RETURN *
```
.. the resulting AST for the 2nd `WITH` clause is missing the `*`.  When it gets rendered back to Cypher, it will render (incorrectly) to this:
```
WITH 'foo' AS foo
WITH 'bar' AS bar
RETURN *
```
Fix is to honor the `returnAll` flag that is set by the parser when `*` is present
> Fix handling of `WITH *, <expr>` 

- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/renderer/PrettyPrintingVisitor.java
- neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/CypherIT.java
- neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/IssueRelatedIT.java
> refactor: Remove superflous whitespaces before `MapExpression` in pretty printer.

- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/renderer/DefaultVisitor.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/renderer/Neo4j5FunctionInvocationVisitor.java
- neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/FunctionsIT.java
This is analogue to how Cypher and the drivers behave.
> feat: Add fallback from `elementId` to `id` on older Neo4j versions.

- neo4j-cypher-dsl-codegen/neo4j-cypher-dsl-codegen-core/src/main/java/org/neo4j/cypherdsl/codegen/core/AbstractClassNameGenerator.java
- neo4j-cypher-dsl-codegen/neo4j-cypher-dsl-codegen-core/src/main/java/org/neo4j/cypherdsl/codegen/core/FieldNameGenerator.java
- neo4j-cypher-dsl-codegen/neo4j-cypher-dsl-codegen-core/src/main/java/org/neo4j/cypherdsl/codegen/core/Identifiers.java
- neo4j-cypher-dsl-examples/neo4j-cypher-dsl-examples-core/src/test/java/org/neo4j/cypherdsl/examples/core/CypherDSLExamplesTest.java
- neo4j-cypher-dsl-examples/neo4j-cypher-dsl-examples-driver/pom.xml
- neo4j-cypher-dsl-schema-name-support/README.adoc
- neo4j-cypher-dsl-schema-name-support/pom.xml
- neo4j-cypher-dsl-schema-name-support/src/main/java/org/neo4j/cypherdsl/support/schema_name/SchemaNames.java
- neo4j-cypher-dsl-schema-name-support/src/test/java/org/neo4j/cypherdsl/support/schema_name/SchemaNamesIT.java
- neo4j-cypher-dsl-schema-name-support/src/test/java/org/neo4j/cypherdsl/support/schema_name/SchemaNamesTest.java
- neo4j-cypher-dsl-test-results/pom.xml
- neo4j-cypher-dsl/pom.xml
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/SymbolicName.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/renderer/DefaultVisitor.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/utils/Strings.java
- neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/renderer/DefaultVisitorTest.java
- pom.xml
* Too many escapes of the backslash
* No need to check for the actual ` and the unicode value
* BUT a need to check for the escaped unicode proper (which is literael
\\u0060, written down as Java String becomes \\\\u0060, no further
escapeing for the regex necessary
> bug: Improve quotation pattern.

- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/StatementBuilder.java
- neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/IssueRelatedIT.java
> fix: Allow `match` after unwind as defined by OpenCypher.

- pom.xml
This way it is correctly configured in all modules and our (actually quite good) test coverage is reported correct.
> build: Define JaCoCo config in plugin-management.

- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/Asterisk.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/Cypher.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/DefaultLoadCSVStatementBuilder.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/DefaultStatementBuilder.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/ExposesReturning.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/ExposesWith.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/Expressions.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/IdentifiableElement.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/Named.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/Property.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/StatementBuilder.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/internal/ScopingStrategy.java
- neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/CypherIT.java
- neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/DefaultStatementBuilderTest.java
- neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/IdentifiableExpressionsIT.java
- neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/IssueRelatedIT.java
This addresses and fixes #547 to some extend. The goal was to allow compilation of
```java
var cypher = Cypher.match(person)
.returning(
person,
Expressions.count(person.relationshipTo(person, "ACTED_IN")).as("acted_in_rel_count")
).build();
```
without aliasing the `person` node with `as`.
This could be achieved by allowing `IdentifiableElement` on the `returning` methods the same way this PR does with the `with` methods. However, in contrast to `with`, `return` does allow non-aliased expressions, so the overload taking in `Expression` must continue to exists. That will rule out to add another overload with a `Collection<SomethingElse>`, as they will have the same type erasure as existing methods. Adding a varg of `IdentifiableElement` will break a gazillion lines of code, even in our …
> refactor: Improve `returning` and `with`.

- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/Clauses.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/Cypher.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/DefaultStatementBuilder.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/ExposesCreate.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/ExposesMatch.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/ExposesReturning.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/Pattern.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/StatementBuilder.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/ast/TypedSubtree.java
- neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/IssueRelatedIT.java
- pom.xml
> refactor: Allow covariant collection overloads for `PatternElement` and `Expression` where sensible.

- neo4j-cypher-dsl-parser/src/test/java/org/neo4j/cypherdsl/parser/CypherParserTest.java
- neo4j-cypher-dsl-parser/src/test/java/org/neo4j/cypherdsl/parser/IdentifiableExpressionsTest.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/internal/ScopingStrategy.java
The `ScopingStrategy` must only leave the scope when leaving the element of entrance, not every element that follows.
Fixes #571.
> fix: Correctly track identifiable elements.

- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/StatementContext.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/StatementContextImpl.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/renderer/DefaultVisitor.java
- neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/IssueRelatedIT.java
This is necessary to keep the generated values constant for the lifetime of a statement.
Otherwise they would be re-resolved by the rendering when the cache overflew. This is probably
not what happened in #585, but what I realised while adding a test for the desired behaviour.
Having an API to access the resolved values might be useful in the future, too.
Fixes #585.
> fix: Move resolved symbolic names into `StatementContext`.

- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/internal/ScopingStrategy.java
- neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/IssueRelatedIT.java
> fix: Open implicit scope when entering a `UNION` clause.

- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/renderer/DefaultVisitor.java
- neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/IssueRelatedIT.java
This fixes #605. Thanks to @GregoryEssertel for spotting this.
> fix: Apply prefixes after potential separator.

- neo4j-cypher-dsl-native-tests/src/main/java/org/neo4j/cypherdsl/graalvm/Application.java
- neo4j-cypher-dsl-parser/src/test/java/org/neo4j/cypherdsl/parser/ExtractionIT.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/StatementCatalog.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/StatementCatalogBuildingVisitor.java
- neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/StatementCatalogBuildingVisitorTest.java
This changes implements #618. The Neo4j documentation speaks about filters and we think it’s a better name to be used in our catalog too. So to unify the access to both property based filters (which filter by conditions) and label existence based filters, the `Condition` type has been renamed `PropertyFilter` and an interface `Filter` has been introduced, together with all required accessors for the label filters.
This closes #618.
> feat: Add label existences conditions to catalog.

- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/CountExpression.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/ExistentialSubquery.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/ExposesSubqueryCall.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/Expressions.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/ImportingWith.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/Predicates.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/Subquery.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/internal/ScopingStrategy.java
- neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/ExpressionsIT.java
- neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/SubqueriesIT.java
This allows for easier composition of queries with those type of subqueries than using the builder throughout a pipeline. As we don’t do a full semantic analysis inside the statement, those overloads don’t do a semantical check whether the passed statements are read-only queries or not. Neither `count` nor `exists` do support updates. If such a query is used, syntactically correct Cypher will be rendered, but that cypher can’t be executed.
The API is argumentwise compatible with `org.neo4j.cypherdsl.core.ExposesSubqueryCall#call(org.neo4j.cypherdsl.core.Statement, org.neo4j.cypherdsl.core.IdentifiableElement…)`.
This closes #578.
> feat: Add overloads for `count` and `exists` taking in a statement and optional imports.

- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/Cypher.java
- neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/IssueRelatedIT.java
> feat: Add `Cypher.withAll` to create a with clause importing all (`*`) variables.

- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/StatementCatalogBuildingVisitor.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/internal/ScopingStrategy.java
- neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/StatementCatalogBuildingVisitorTest.java
> refactor: Use sorted sets everywhere to keep orders of identifiables in the catalog close to users expectations.

- README.adoc
- neo4j-cypher-dsl-parser/src/main/java/org/neo4j/cypherdsl/parser/Options.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/BuiltInFunctions.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/Cypher.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/Functions.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/UseClauseImpl.java
- neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/FunctionsIT.java
- neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/FunctionsTest.java
- neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/StatementCatalogBuildingVisitorTest.java
- neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/UseIT.java
Also allow possible usecases of `graph.byName` in `Cypher.use`.
CLoses #728.
> feat: Provide all functions in the `graph.*` namespaces.

- .github/workflows/build.yml
- neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/FunctionsIT.java
- neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/FunctionsTest.java
- pom.xml
The Maven Site plugin fails on that. But doing so, brings us back to a Non-JDK-21 compliant version which in turn then doesn't let us do inline mocks proper.
> build: Remove explicit management of bytebuddy.

- neo4j-cypher-dsl-codegen/neo4j-cypher-dsl-codegen-core/src/main/java/org/neo4j/cypherdsl/codegen/core/Configuration.java
- neo4j-cypher-dsl-codegen/neo4j-cypher-dsl-codegen-core/src/main/java/org/neo4j/cypherdsl/codegen/core/FieldNameGenerator.java
- neo4j-cypher-dsl-codegen/neo4j-cypher-dsl-codegen-core/src/test/java/org/neo4j/cypherdsl/codegen/core/ConfigurationTest.java
> feat: Make fieldname generator configurable.

- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/internal/ScopingStrategy.java
- neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/IssueRelatedIT.java
> fix: Make sure local scope is cleared after leaving subquery expressions.

- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/LiteralBase.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/Merge.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/StatementCatalogBuildingVisitor.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/internal/ScopingStrategy.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/renderer/DefaultVisitor.java
- neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/IssueRelatedIT.java
> fix: Including aliasing in scoping strategey, too.

- neo4j-cypher-dsl-parser/src/main/java/org/neo4j/cypherdsl/parser/CypherDslASTFactory.java
- neo4j-cypher-dsl-parser/src/main/java/org/neo4j/cypherdsl/parser/NodeAtom.java
- neo4j-cypher-dsl-parser/src/main/java/org/neo4j/cypherdsl/parser/PathAtom.java
- neo4j-cypher-dsl-parser/src/test/java/org/neo4j/cypherdsl/parser/CypherParserTest.java
- neo4j-cypher-dsl-parser/src/test/java/org/neo4j/cypherdsl/parser/QPPTest.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/Cypher.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/ExposesProperties.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/InternalNodeImpl.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/Node.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/NodeBase.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/Relationship.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/RelationshipBase.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/RelationshipChain.java
- neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/CypherIT.java
This allows `where` to be used on `Node` and `Relationship`.
While it closes #858 it is merely the groundwork to support parsing QPP.
> feat: Add support for predicates inside pattern elements.

- neo4j-cypher-dsl-parser/src/test/java/org/neo4j/cypherdsl/parser/CypherParserTest.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/BuiltInFunctions.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/Cypher.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/internal/ScopingStrategy.java
- neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/IssueRelatedIT.java
> fix: Driving symbolic names for list predicate function must not be scoped.

- neo4j-cypher-dsl-examples/neo4j-cypher-dsl-examples-sdn6/src/main/java/org/neo4j/cypherdsl/examples/sdn6/books/Book.java
- neo4j-cypher-dsl-examples/neo4j-cypher-dsl-examples-sdn6/src/main/java/org/neo4j/cypherdsl/examples/sdn6/books/BookGenre.java
- neo4j-cypher-dsl-examples/neo4j-cypher-dsl-examples-sdn6/src/main/java/org/neo4j/cypherdsl/examples/sdn6/books/UserDetails.java
- neo4j-cypher-dsl-examples/neo4j-cypher-dsl-examples-sdn6/src/main/java/org/neo4j/cypherdsl/examples/sdn6/books/UserPreferences.java
- neo4j-cypher-dsl-examples/neo4j-cypher-dsl-examples-sdn6/src/main/java/org/neo4j/cypherdsl/examples/sdn6/books/UserSuggestionActivity.java
- neo4j-cypher-dsl-examples/neo4j-cypher-dsl-examples-sdn6/src/main/java/org/neo4j/cypherdsl/examples/sdn6/books/package-info.java
- neo4j-cypher-dsl-examples/neo4j-cypher-dsl-examples-sdn6/src/test/java/org/neo4j/cypherdsl/examples/sdn6/books/ScopingTest.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/FunctionInvocation.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/NodeBase.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/PatternExpression.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/PatternExpressionImpl.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/renderer/DefaultVisitor.java
- neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/FunctionsIT.java
- neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/IssueRelatedIT.java
A marker interface has been introduced to check for pattern expressions. When a symbolic names needs to be rendered, it its checked if it has been already resolved when inside a pattern expressions. If so, it will be rendered as normal, otherwise it will be skipped.
Closes #1014
> fix: Don’t introduce new names in pattern expressions.

- README.adoc
This is now 2022.9.x, not 2022.8.x.
> Update latest version supporting JDK 8 in README

- README.adoc
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/DecoratedQuery.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/renderer/ConfigurableRenderer.java
- neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/renderer/Dialect.java
- neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/Cypher5IT.java
- neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/CypherIT.java
- neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/IssueRelatedIT.java
When selecting this dialect, Cypher-DSL ensures that all statements are prefixed with `CYPHER 5` when rendered to ensure compatiblity with Neo4j 2025.x in the future to come without jumping on Cypher 25 right now.
This has not been implemented as a visitor handler, but as post rendering operations to cater for nested statements such as subqueries, decorated queries and use queries. It would be a lot more work to figure out if those has been already prefixed or not.
Closes #1153.
> feat: Introduce Dialect 5.26
